import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
const engine=html.match(/<script id="gsg-sharpen-engine">([\s\S]*?)<\/script>/)?.[1];
assert(engine,'Sharpen engine missing');
const frozen=engine.slice(0,engine.indexOf('(function(){'));
const sandbox={Object,console};vm.createContext(sandbox);
vm.runInContext(frozen+';this.out={GOLF_SHARPEN_REGIONS,GOLF_SHARPEN_ROUTES,GOLF_SHARPEN_RESULTS,GOLF_SHARPEN_ASSETS,GSS_QUESTION_LEARNING};',sandbox);
const {GOLF_SHARPEN_REGIONS:R,GOLF_SHARPEN_ROUTES:Q,GOLF_SHARPEN_RESULTS:Z,GOLF_SHARPEN_ASSETS:A,GSS_QUESTION_LEARNING:QL}=sandbox.out;
const required=['tee','recovery','approach','green','putting'];
assert.deepEqual(Object.keys(R),required,'Five one-hole decision zones must be authoritative and ordered');
const ids=new Set();
const issueSignatures=new Set(),focusSignatures=new Set();
for(const [rid,r] of Object.entries(R)){
 assert.equal(r.number,required.indexOf(rid)+1,rid+' has wrong round order');
 assert.equal(typeof r.club,'string',rid+' does not carry its bag identity');
 assert(r.issues.length>=3&&r.issues.length<=5,rid+' must have 3-5 issues');
 const issueSignature=r.issues.map(x=>x.label).sort().join('|');assert(!issueSignatures.has(issueSignature),rid+' duplicates another moment journey');issueSignatures.add(issueSignature);
 for(const issue of r.issues){assert(!ids.has(issue.id),'duplicate issue '+issue.id);ids.add(issue.id);assert(Q[issue.route],'unreachable route '+issue.route)}
 const focusSignature=Object.values(Z).filter(x=>x.regionId===rid).map(x=>x.focus).sort().join('|');assert(!focusSignatures.has(focusSignature),rid+' duplicates another moment focus set');focusSignatures.add(focusSignature);
}
for(const [qid,q] of Object.entries(Q)) for(const answer of q.answers) assert(Z[answer.resultId],qid+' has missing result');
for(const [id,r] of Object.entries(Z)){
 for(const key of ['read','coachLens','watchFor','focus','cue']) assert(r[key],id+' missing '+key);
 assert(Array.isArray(r.learningKeys)&&r.learningKeys.length,id+' lacks semantic learning keys');
 assert(!/^The useful gain is often|^The final outcome is the symptom/.test(r.coachLens),id+' uses generic fallback coaching');
 assert(r.assetIds.length>=1&&r.assetIds.length<=3,id+' must route to 1-3 assets');
 assert.equal(r.confidence,'guided-hypothesis',id+' crosses claim boundary');
 assert.equal(r.reviewStatus,'launch-reviewed',id+' lacks review');assert(r.sources.length,id+' lacks source support');for(const source of r.sources)assert(/^https:\/\/(www\.)?(pga\.com|usga\.org)\//.test(source),id+' uses a non-primary source: '+source);
 for(const aid of r.assetIds){assert(A[aid],id+' missing asset '+aid);assert.equal(A[aid].launchStatus,'approved',id+' links unapproved asset');assert(Array.isArray(A[aid].learningKeys),aid+' lacks semantic keys');assert(r.learningKeys.some(k=>A[aid].learningKeys.includes(k)),id+' is semantically incompatible with '+aid)}
 if(id.startsWith('putting_pace')) assert(/pace|finish|short|long/i.test(r.focus),'pace route has non-pace focus');
 if(id.startsWith('tee_curve')) assert(/start|curve|corridor/i.test(r.focus),'curve route has non-flight focus');
 if(id.startsWith('first_')||id.startsWith('pressure_')) assert(!/swing fix|clubface path/i.test(r.focus),'mental route invents mechanical diagnosis');
}
for(const [id,a] of Object.entries(A)){assert(a.destination&&Array.isArray(a.routeParams),id+' lacks exact destination');assert(!/generic|todo|later/i.test(a.title+a.description),id+' is generic/deferred')}
const mini=Object.entries(A).filter(([,a])=>a.type==='mini');
assert(mini.length>=6,'focused legacy mini-session coverage is incomplete');
for(const [id,a] of mini){assert.equal(a.routeParams[1].length,3,id+' must contain exactly three approved question IDs');const covered=new Set(a.routeParams[1].flatMap(qid=>{assert(QL[qid],id+' question '+qid+' lacks reviewed semantic keys');return QL[qid]}));for(const key of a.learningKeys)assert(covered.has(key),id+' claims learning not covered by its questions: '+key)}
assert(!Object.values(A).some(a=>a.destination==='startHole'),'generic Play a Hole destination remains reachable');
assert(Object.values(A).filter(a=>a.destination==='startSharpenHole').length>=4,'exact authored hole mappings incomplete');
assert.equal(A.debrief.destination,'showDebrief','19th Hole promise must open the debrief directly');
assert(/19TH HOLE DEBRIEF[\s\S]{0,300}GameSharpGolfSharpen\.returnFromAsset/.test(html)||/GameSharpGolfSharpen\.returnFromAsset[\s\S]{0,300}19TH HOLE DEBRIEF/.test(html),'debrief native close loses Sharpen context');
for(const id of ['QE5_040','QE5_041','QE5_042','QE5_043','QE5_044','QE5_045']){assert.equal((html.match(new RegExp('"id"\\s*:\\s*"'+id+'"','g'))||[]).length,1,id+' must exist exactly once');assert(new RegExp('"id"\\s*:\\s*"'+id+'"[\\s\\S]{0,500}"visual_must_show"\\s*:\\s*false').test(html),id+' unexpectedly requires an uncontracted visual')}
assert(/else if\(id === 'sharpen'\)\{ GameSharpGolfSharpen\.open\(\); \}/.test(html),'Sharpen must open the round journey directly');
assert.equal((html.match(/<span class="nav-label">Sharpen<\/span>/g)||[]).length,3,'every bottom navigation must call the feature Sharpen');
assert(!/<span class="nav-label">Practice<\/span>/.test(html),'legacy Practice navigation label remains');
assert(!/else if\(id === 'sharpen'\)\{ renderSharpen\(\)/.test(html),'Legacy lobby remains primary');
assert(/prefers-reduced-motion:reduce/.test(html),'Reduced-motion treatment missing');
assert(/Where did the round feel hardest\?/.test(html),'one-hole entry question missing');
assert(!/data-mode="(prepare|sharpen|reflect)"/.test(html),'retired preliminary Sharpen menu remains reachable');
assert(!/function moments\(mode\)/.test(html),'retired eight-stage journey remains implemented');
assert(fs.existsSync(new URL('./gamesharp-one-hole-v1.png',import.meta.url)),'one-hole source artwork missing');
const holeWebp=new URL('./gamesharp-one-hole-v1.webp',import.meta.url),holeJpeg=new URL('./gamesharp-one-hole-v1.jpg',import.meta.url);assert(fs.existsSync(holeWebp),'optimized one-hole artwork missing');assert(fs.statSync(holeWebp).size<=160000,'one-hole artwork exceeds 160KB mid-tier-phone budget');assert(fs.existsSync(holeJpeg)&&fs.statSync(holeJpeg).size<=300000,'Safari JPEG fallback is missing or too heavy');assert(/id="gss-hole-image"[^>]+gamesharp-one-hole-v1\.webp\?v=18/.test(html),'Sharpen does not render a real recoverable one-hole image element');
const sw=fs.readFileSync(new URL('./sw.js',import.meta.url),'utf8');assert(/gamesharp-one-hole-v1\.webp/.test(sw)&&/gamesharp-one-hole-v1\.jpg/.test(sw),'one-hole primary and Safari fallback are unavailable in the offline course shell');assert(!/gamesharp-round-journey-v1\.(?:png|webp)/.test(sw),'retired winding journey remains in the offline shell');assert(!/gamesharp-round-journey-v1\.(?:png|webp)/.test(html),'retired winding journey artwork remains referenced by the app');
assert(/const CACHE = 'gamesharp-golf-v22'/.test(sw),'release cache version must evict the card-based Home shell');
assert(/id="gss-cinema"[^>]*hidden/.test(html),'persistent one-hole visual layer missing');
assert(/\.gss-cinema\[data-stage="entry"\]\{[^}]*aspect-ratio:943\/1680[^}]*background-size:100% 100%/.test(html),'the complete hole is not visible on Sharpen entry');
assert(/const ZONE_ORDER=\['tee','recovery','approach','green','putting'\]/.test(html),'five-zone order is not authoritative');
assert(/function cinema\(stage,moment='tee',resultId=null\)/.test(html),'authoritative one-hole renderer missing');
assert(/const zoneMarkup=\(interactive,current\)=>interactive\?ZONE_ORDER\.map/.test(html),'entry hotspots do not derive from one authoritative renderer');
assert(/const zoneVisualMarkup=\(moment,issueId\)=>/.test(html),'selected Sharpen moment lacks an authoritative issue-aware visual renderer');
for(const token of ['gss-corridor-a','gss-escape-line','gss-approach-arc','gss-bounce-3','gss-putt-line'])assert(html.includes(token),'unique region visual missing: '+token);
assert(/cinemaEl\.addEventListener\('click',[\s\S]{0,180}issues\(b\.dataset\.zone\)/.test(html),'hole hotspots do not route directly to their learning area');
assert(/\.gss-hole-zone\{[^}]*min-width:48px[^}]*min-height:48px/.test(html),'hole hotspots must preserve 48px touch targets');
for(const rid of required)assert(new RegExp(`\\.gss-hole-zone\\[data-zone="${rid}"\\]\\{left:[0-9.]+%;top:[0-9.]+%\\}`).test(html),`hole hotspot ${rid} has no explicit visual coordinate`);
for(const rid of required)assert(new RegExp(`data-moment="${rid}"[^}]+\\.gss-hole-image`).test(html),`Sharpen moment ${rid} lacks a distinct camera crop`);
for(const rid of required)assert(new RegExp(`data-moment="${rid}"[^}]+\\.gss-shot-(?:ball|block)`).test(html),`Sharpen moment ${rid} lacks a distinct instructional overlay`);
assert(/if\(stage!=='entry'\)cinemaEl\.insertAdjacentHTML\('beforeend',zoneVisualMarkup\(moment,state\.issueId\)\)/.test(html),'selected issue does not render its synchronized visual');
for(const issue of ['curve','start','strike','wind','lie','club','contact','bunker','read','pace','short'])assert(new RegExp(`key==='${issue}'|data-variant="${issue}"`).test(html),'issue-level visual variant missing: '+issue);
assert(!/gss-zone-pulse|gssZoneBreathe/.test(html),'retired five-circle animation remains implemented');
assert(/@media\(prefers-reduced-motion:reduce\)[\s\S]{0,300}\.gss-putt-line[^}]*animation:none/.test(html),'reduced motion does not preserve shot information');
assert(!/heroProbe/.test(html)&&/HERO_JPEG='gamesharp-one-hole-v1\.jpg\?v=18'/.test(html)&&/heroFormat==='webp'\)loadHoleHero\(false\)/.test(html),'one-hole image does not fall back from WebP to JPEG');
assert(/addEventListener\('online',[\s\S]{0,150}loadHoleHero\(true\)/.test(html)&&/data-gss-image-retry/.test(html),'one-hole image failure cannot recover automatically or manually');
assert(/Course image unavailable\. Choose the part of the hole/.test(html),'one-hole image failure lacks a usable text fallback');
assert(/gss-hole-image-failed\[data-stage="entry"\][^}]*display:grid/.test(html)&&/gss-hole-image-failed\[data-stage="entry"\] \.gss-hole-zone\{[^}]*position:relative/.test(html),'image-failure routes are not laid out as a usable grid');
assert(/result\?result\.cue/.test(html),'one-hole result caption must derive from the authoritative result cue');
assert(/const bagStatus=rid=>/.test(html)&&/const bagMarkup=\(\)=>/.test(html),'bag is not derived from Sharpen history');
assert(/data-bag-zone/.test(html)&&/b\.dataset\.bagZone\)issues\(b\.dataset\.bagZone\)/.test(html),'bag is disconnected from the same five-zone router');
assert(/id="profile-sharpen-bag"/.test(html)&&/const bagSummary=\(\)=>/.test(html)&&/openZone\(rid,from\)/.test(html),'Review bag is not a projection of the same Sharpen state and router');
assert(/Learning activity—not a measure of your swing\./.test(html),'bag state crosses the claim boundary');
assert(/current focus|recently tested|ready to revisit/.test(html),'bag lacks transparent living states');
assert(/cinema\('issue',rid\)/.test(html),'persistent illustration missing from symptom selection');
assert(/cinema\('route',state\.regionId\)/.test(html),'persistent illustration missing from distinction');
assert(/cinema\('result',r\.regionId,id\)/.test(html),'persistent illustration missing from focus result');
assert(/cinema\('result',r\.regionId,saved\.resultId\)/.test(html),'saved-focus return loses cinematic context');
assert(!/class="gss-journey-visual"/.test(html),'retired recreated illustration remains reachable');
assert(/data-share-map/.test(html)&&/function shareJourney\(\)/.test(html)&&/gamesharp-bag-focus\.jpg/.test(html),'one-hole bag share card missing');
assert(/focusHistory/.test(html)&&/function habitStats\(\)|const habitStats=/.test(html)&&/function takeFocus\(\)/.test(html)&&/function checkFocus\(/.test(html),'take-test-return habit loop missing');
assert(/Take this to your next round →/.test(html)&&/How did it go\?/.test(html),'practice loop language missing');
assert(/KEY='gsg_sharpen_state_v5',LEGACY_KEY='gsg_sharpen_state_v4'/.test(html),'five-zone Sharpen state migration missing');
assert(/state\.saved&&!GOLF_SHARPEN_RESULTS\[state\.saved\.resultId\]/.test(html),'incompatible winding-journey state is not safely ignored');
assert(/const focus=`<section class="gss-result-lead"[\s\S]{0,1000}Test it now[\s\S]{0,700}<details class="gss-why"/.test(html),'result does not lead with one focus and one test before explanation');
assert(!/data-save>Save this focus/.test(html)&&/Take this to your next round →/.test(html),'benefit-led take-to-round language missing');
assert(/aria-modal="true"/.test(html)&&/if\(e\.key==='Tab'\)/.test(html),'Modal focus contract missing');
assert(/function set\(html,label\)\{[^}]*el\.scrollTop=0/.test(html),'Sharpen stage transitions can inherit stale mobile scroll');
assert(/returnPending/.test(html)&&/returnFromAsset/.test(html),'Asset return context missing');
assert(/SHARPEN FOCUS/.test(html)&&/During this rep:/.test(html),'Legacy asset does not carry Sharpen learning context');
assert(!/<h3>The Read<\/h3>/.test(html),'duplicated Read section remains visible');
assert(/resultViews/.test(html)&&/gss-result\$\{compact\?' compact'/.test(html),'return-player progressive disclosure missing');
assert(/PLAY WITH SEVE’S IMAGINATION/.test(html)&&/europeantour\.com\/dpworld-tour\/news\/video\/the-best-of-seve-ballesteros/.test(html),'sourced Seve identity moment missing');
assert((html.match(/Find the Culprit ·/g)||[]).length>=8,'Shot Clinic is not explicitly wired as Find the Culprit');
assert(/function exitQuiz\(\)\{\s*if\(window\.GameSharpGolfSharpen&&GameSharpGolfSharpen\.returnFromAsset\(\)\) return;/.test(html),'focused mini-session native exit loses Sharpen context');
assert((html.match(/hvh-back" onclick="if\(!GameSharpGolfSharpen\.returnFromAsset\(\)\)/g)||[]).length>=2,'focused hole native exit loses Sharpen context');
assert(!/function startCrashCourse\(/.test(html)&&!/onclick="startCrashCourse\(\)"/.test(html),'redundant Crash Course launcher remains reachable');
assert(!/id="home-depth"/.test(html)&&!/<details class="home-more">/.test(html),'Today must preserve the two-action Daily + Play a Hole hierarchy');
assert(!/Change grip immediately/.test(html),'soft Daily distractor remains launch-reachable');
assert(/Choice copy must describe the shot, never grade it before commitment/.test(html)&&/lower-risk\|aggressive/.test(html),'Play-a-Hole neutrality is not structurally enforced');
assert(/\.gss-hole-zone\{[^}]*min-width:48px[^}]*min-height:48px/.test(html),'48px one-hole target missing');
console.log(JSON.stringify({ok:true,regions:Object.keys(R).length,routes:Object.keys(Q).length,results:Object.keys(Z).length,assets:Object.keys(A).length},null,2));
