import fs from 'node:fs';
import assert from 'node:assert/strict';

const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');

assert(/function gsPrepareHomeHero\(\)[\s\S]{0,400}home\.dataset\.heroStable = 'true'/.test(html),'home hero must resolve to a stable presentation');
assert(!/gsHomeHeroTimer = window\.setTimeout\(gsCollapseHomeHero/.test(html),'home must not collapse on a timer');
assert(!/addEventListener\('(pointerdown|scroll|touchmove)', gsCollapseHomeHero/.test(html),'touch and scroll must not move the home layout');
assert(!/#view-home \.home-hero,[\s\S]{0,120}transition:(max-height|height|margin|padding)/.test(html),'home must not animate layout dimensions');
assert.equal((html.match(/<button class="home-play"/g)||[]).length,1,'home must expose one direct secondary play choice');
assert(/<div class="daily-card">[\s\S]{0,700}<button class="home-play"/.test(html),'Daily and Play a Hole must be the only ordered Home actions');
assert(/savedHole=loadHoleSession\(\)[\s\S]{0,500}hod\.name} · Shot \$\{shot}[\s\S]{0,300}setAttribute\('aria-label',`Resume/.test(html),'home must advertise the exact interrupted hole that Play a Hole will resume');
assert(/openSaved\(from\)\{open\(from\);if\(state\.saved/.test(html),'saved Sharpen focus must reopen its exact result context');
assert(!/<button class="mode-card"/.test(html),'legacy competing home mode cards remain');
assert(!/<details class="home-more">/.test(html)&&!/<button class="home-depth"/.test(html),'Home must not expose a third action or feature directory');
assert(!/id="dc-streak-text"/.test(html),'Home must not repeat the streak already shown in its header');
assert(/#view-home \{[^}]*touch-action:pan-y[^}]*overflow-anchor:none/.test(html),'home mobile scrolling contract missing');
assert(/#view-home \{[^}]*-webkit-overflow-scrolling:touch[^}]*isolation:isolate/.test(html),'home lacks an iPhone-native scroll and stacking boundary');
assert(/#view-home \.daily-card,#view-home \.home-play\{[^}]*z-index:2[^}]*pointer-events:auto/.test(html),'home actions can be obscured by decorative layers');
assert(/button \{[^}]*touch-action:manipulation/.test(html),'mobile buttons lack deterministic tap handling');
assert(/#view-home \{[^}]*background:[^}]*scroll[^}]*overflow-y:scroll/.test(html),'home must use an iPhone-safe scrolling background and explicit scroll container');
assert(/function gsStartHomeReveal\(\)[\s\S]{0,700}gsg_home_reveal_v21/.test(html)&&/gs-home-reveal \.daily-card[^{]*\{[^}]*1\.85s forwards/.test(html),'Home does not provide a course-first reveal before its decisions');
assert(/prefers-reduced-motion:reduce[^}]*#view-home\.gs-home-reveal/.test(html),'Home reveal does not respect reduced motion');
assert(!/\.gss-option:hover,\.gss-option:focus-visible/.test(html)&&/@media\(hover:hover\) and \(pointer:fine\)\{\.gss-option:hover/.test(html),'touch can leave an unchosen Sharpen option looking selected');
assert(/#view-home > \* \{ flex-shrink:0; \}/.test(html),'home sections must not shrink until the page has no scrollable distance');
assert(/#app \{[^}]*height:100dvh[^}]*min-height:0/.test(html)&&/\.view \{[^}]*height:100dvh[^}]*min-height:0/.test(html),'app shell lacks a dynamic mobile viewport scroll contract');
assert(!/function open\(from\)[\s\S]{0,400}document\.body\.style\.overflow='hidden'/.test(html),'Sharpen must not mutate the body scroll lock ad hoc');
assert.equal((html.match(/<button class="nav-item/g)||[]).length,9,'all bottom navigation controls must be semantic buttons');
assert(!/<div class="nav-item/.test(html),'inaccessible bottom navigation implementation remains');
assert(/if\(active&&active\.classList\.contains\('active'\)\)\{viewScroll\[id\]=0;active\.scrollTop=0;return\}/.test(html),'reselecting a tab must return it to the top');
assert(/id="profile-btn"[^>]*aria-label="Open progress and profile"/.test(html),'profile control lacks an accessible name');
assert(/@media\(prefers-reduced-motion:reduce\)/.test(html),'reduced-motion contract missing');
assert(/@media\(orientation:landscape\) and \(max-height:500px\)[\s\S]{0,500}#view-home \.home-hero\{height:72px/.test(html),'landscape home compaction missing');
assert(/\(node\.choices \|\| \[\]\)\.forEach[\s\S]{0,180}document\.createElement\('button'\);[\s\S]{0,100}card\.type = 'button'/.test(html),'Play a Hole decisions must be semantic keyboard-operable buttons');
assert(/#shot-panel \.decision-card'\)\.forEach\(c => \{[\s\S]{0,120}c\.disabled = true/.test(html),'committed Play a Hole choices must expose their locked state');
for(const id of ['db-fairways','db-gir','db-putts','db-score'])assert(new RegExp(`<label[^>]+for="${id}"`).test(html),`Debrief input ${id} lacks a programmatic label`);
assert.equal((html.match(/class="db-sign[^>]+aria-label="(?:Over|Even|Under) par"[^>]+aria-pressed=/g)||[]).length,3,'debrief score-sign controls must expose name and state');
assert(/gaps\[0\]\.score > 0 \? gaps\[0\] : \{[\s\S]{0,220}One Decision to Revisit/.test(html),'a balanced scorecard must not be assigned a contradictory negative leak');

console.log(JSON.stringify({ok:true,homePrimaryActions:2,playChoices:1,homeCompetingDoors:0,semanticNavButtons:9},null,2));
